/* TYPEN INITIALISIEREN */
  INSERT INTO MARKER (MARKER_TITLE)
   VALUES('Eng');
  INSERT INTO CONDITION(CONID, CONDITION_TITLE, ORIGINAL_CONNR)
   VALUES ('**', 'Marke postfrisch', 1)
        , ('*', 'Marke ungestempelt', 2)
        , ('x', 'Marke gestempelt', 3)
        , ('~', 'Marke anders entwertet')
        , ('Bl **', 'Block postfrisch', 11)
        , ('Bl *', 'Block ungestempelt', 12)
        , ('BL x', 'Block gestempelt', 13)
        , ('BL SoSt', 'Block Sonderstempel', 14)
        , ('BL ESt', 'Block Ersttagsstempel', 15)
        , ('ZDr **', 'Zusammendruck postfrisch', 21)
        , ('ZDr *', 'Zusammendruck ungestempelt', 22)
        , ('ZDr x', 'Zusammendruck gestempelt', 23)
        , ('HBl **', 'Heftchenblatt postfrisch', 24)
        , ('HBl x', 'Heftchenblatt gestempelt', 25)
        , ('KB **', 'Kleinbogen postfrisch', 26)
        , ('KB x', 'Kleinbogen gestempelt', 27)
        , ('KB SoSt', 'Kleinbogen Sonderstempel', 28)
        , ('KB ESt', 'Kleinbogen Ersttagsstempel', 29)
        , ('GS *', 'Ganzsache ungestempelt', 32)
        , ('GS x', 'Ganzsache gestempelt', 33)
        , ('FDC', 'Ersttagsbrief', 34)
        , ('PK *', 'Postkarte ungestempelt', 35)
        , ('PK x', 'Postkarte gestempelt', 36)
        , ('Br x', 'Brief gestempelt', 37)
        , ('GB x', 'Gedenkblatt gestempelt', 38)
        , ('SoBr x', 'Sonderbrief gestempelt', 39)
        , ('GSA *', 'Ganzsachenausschnitt ungestempelt', 42)
        , ('GSA x', 'Ganzsachenausschnitt gestempelt', 43)
        , ('Bg **', 'Bogen postfrisch', 44)
        , ('Bg x', 'Bogen gestempelt', 45)
        , ('MH **', 'Markenheft postfrisch', 46)
        , ('MH x', 'Markenheft gestempelt', 47);
/* HIERARCHIEN INITIALISIEREN */
  INSERT INTO CATALOG (LFDNR_1, LFDNR_2, FATHER, LAYER
                      , ID, TITLE)
  VALUES(1, 2, 1, 1, 'Alle', 'Briefmarken');
  INSERT INTO LOCATION (LFDNR_1, LFDNR_2, FATHER, LAYER
                      , ID, TITLE)
  VALUES(1, 2, 1, 1, 'Alle', 'Standorte');
  INSERT INTO DESIGN (LFDNR_1, LFDNR_2, FATHER, LAYER
                      , ID, TITLE)
  VALUES(1, 2, 1, 1, 'Alle', 'Motive');
/* KATALOGE EINFUEGEN */
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'Alle'   , 'n_Kat'  , 'nicht katalogisiert','');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'n_Kat'  , 'Kat'    , 'alle Kataloge','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'n_Kat'  , 'Vig'    , 'Vignetten','');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Vig'    , 'amtl'   , 'Ausgaben','');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Vig'    , 'Cind'   , 'Cinderella','');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Cind'   , 'Exil'   , 'Exilregierungen','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'Kat'    , 'e_Kon'  , 'einzelne Kontinente','');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'e_Kon'  , 'm_Kon'  , 'mehrere Kontinente','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'm_Kon'  , 'Mtv'    , 'Motive','');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Mtv'    , 'Klas'   , 'Klassik','(vor 1900)');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Klas'   , 'UNO'    , 'Vereinte Nationen','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'Mtv'    , 'Gem'    , 'Gemälde','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'Gem'    , 'Gem E'  , 'Gemälde Europa','');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Gem'    , 'LuF'    , 'Meilensteine der Luftfahrt','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'LuF'    , 'LUF Aus', 'Meilensteine der Luftfahrt Australien, Antarktis, Asien','');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'LUF Aus', 'LuF E'  , 'Meilensteine der Luftfahrt Europa','');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'LUF Aus', 'LuF Am' , 'Meilensteine der Luftfahrt Amerika','');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'LUF Aus', 'LuF Af' , 'Meilensteine der Luftfahrt Afrika','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'Klas'   , 'Klas Au', 'Klassik Australien, Asien','(vor 1900)');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Klas Au', 'Klas Af', 'Klassik Süd-Amerika, Afrika','(vor 1900)');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Klas Af', 'Klas Am', 'Klassik Nord und Mittel-Amerika','(vor 1900)');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Klas Am', 'Klas E' , 'Klassik Europa','(vor 1900)');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'LuF'    , 'Jubi'   , 'Jubiläen','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'Jubi'   , '40 BRD' , '40 Jahre Bundesrepublik','');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', '40 BRD' , '50 TdB' , '50 Jahre Tag der Briefmarke','');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', '50 TdB' , '500 Po' , '500 Jahre Post','');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Jubi'   , 'FehBr'  , 'Fehler auf Briefmarken','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'FehBr'  , 'FehBr Ü', 'Briefmarken Fehler Übersee','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'FehBr'  , 'FehBr E', 'Briefmarken Fehler Europa','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'm_Kon'  , 'UNO'    , 'UNO-Spezial','2020');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'e_Kon'  , 'AS'     , 'Asien','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'AS'     , 'Ü10'    , 'Naher Osten','2004');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Ü10'    , 'Ü 9'    , 'Mittel- und Ostasien','2003');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Ü10'    , 'Ü 8'    , 'Süd- und Südostasien','2003');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'AS'     , 'AUS'    , 'Australien','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'AUS'    , 'Ü 7'    , 'Australien Ozeanien Antarktis','2002/2003');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'AUS'    , 'AF'     , 'Afrika','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'AF'     , 'Ü 6'    , 'Süd- und Zentralafrika','2002');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Ü 6'    , 'Ü 5'    , 'Westafrika','2001/2002');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Ü 5'    , 'Ü 4'    , 'Nord- und Ostafrika','2002');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'AF'     , 'AM'     , 'Amerika','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'AM'     , 'Ü 3'    , 'Südamerika','2001');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Ü 3'    , 'Ü 2'    , 'Karibische Inseln','2000');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'Ü 2'    , 'Ü 1'    , 'Nord und Mittelamerika','2000');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'AM'     , 'E'      , 'Europa','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'E'      , 'E 7'    , 'Osteuropa','2015');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'E 7'    , 'E 6'    , 'Westeuropa','2015');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'E 6'    , 'E 5'    , 'Nordeuropa','2015');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'E 5'    , 'E 4'    , 'Südosteuropa','2015');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'E 4'    , 'E 3'    , 'Südeuropa','2015');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'E 3'    , 'E 2'    , 'Südwesteuropa','2015');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'E 2'    , 'E 1'    , 'Mitteleuropa','2015');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'E 1'    , 'D'      , 'Deutschland','');
  EXEC SP_HIERACHY_ADD_CHILD ('CATALOG', 'D'      , 'DS1'    , 'Deutschland Spezial Band 1','2016');
  EXEC SP_HIERACHY_ADD_BEFORE('CATALOG', 'DS1'    , 'DS2'    , 'Deutschland Spezial Band 2','2016');
/* STANDORTE EINFUEGEN */
  EXEC SP_HIERACHY_ADD_CHILD ('LOCATION', 'Alle'   , 'KinZ'  , 'Kinderzimmer','');
  EXEC SP_HIERACHY_ADD_CHILD ('LOCATION', 'KinZ'   , 'RgFs'  , 'Regal am Fenster','');
  EXEC SP_HIERACHY_ADD_CHILD ('LOCATION', 'Alle'   , 'KinZ'  , 'Kinderzimmer','');
  EXEC SP_HIERACHY_ADD_BEFORE('LOCATION', 'BlK1'   , 'BlK2'  , 'Billy-Regal klein II','');
  EXEC SP_HIERACHY_ADD_BEFORE('LOCATION', 'BlK2'   , 'BlK3'  , 'Billy-Regal klein III','');
  EXEC SP_HIERACHY_ADD_BEFORE('LOCATION', 'KinZ'   , 'Flur'  , 'Flur','');
  EXEC SP_HIERACHY_ADD_CHILD ('LOCATION', 'Flur'   , 'Bl w'  , 'Billy-Regal weiß','');
  EXEC SP_HIERACHY_ADD_BEFORE('LOCATION', 'Flur'   , 'WhZi'  , 'Wohnzimmer','');
  EXEC SP_HIERACHY_ADD_CHILD ('LOCATION', 'WhZi'   , 'SchB'  , 'Schrank am Balkon','');
  EXEC SP_HIERACHY_ADD_BEFORE('LOCATION', 'SchB'   , 'SchF'  , 'Schrank zum Flur','');
  EXEC SP_HIERACHY_ADD_BEFORE('LOCATION', 'SchF'   , 'RgSw'  , 'Regal schwarz','');
  EXEC SP_HIERACHY_ADD_BEFORE('LOCATION', 'RgSw'   , 'DrRG'  , 'Regal unter dem Drucker','');
/* DESIGN EINFUEGEN */
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', 'Alle'   , '9000'  , 'Post','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '9000'   , '9300'  , 'Posthorn','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '9300'   , '9200'  , 'Postgebäude','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '9200'   , '9100'  , 'Briefträger, Postbeamte','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '9000'   , '8000'  , 'Zusammenschlüsse, Bündnisse, Vereinigungen, Organisationen, Verbände','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '8000'   , '8400'  , 'andere Verbände','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '8400'   , '8410'  , 'Frauenverbände','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '8400'   , '8300'  , 'Wirtschaftsverbände','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '8300'   , '8320'  , 'RGB','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '8320'   , '8310'  , 'EG','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '8300'   , '8200'  , 'Postorganisationen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '8200'   , '8240'  , 'UPU','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '8240'   , '8230'  , 'Gemeinschaftsausgaben','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '8230'   , '8220'  , 'Mitläufer','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '8220'   , '8210'  , 'CEPT','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '8200'   , '8100'  , 'politische Organisationen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '8100'   , '8120'  , 'EU','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '8120'   , '8110'  , 'UNO','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '8110'   , '8111'  , 'UNICEF','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '8000'   , '7000'  , 'Geschichte, Politik, Staat, Gesellschaft, Religion, Kirche','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '7000'   , '7700'  , 'Staatliche Symbole','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '7700'   , '7740'  , 'Landkarten, Vermessung','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7740'   , '7730'  , 'Symbole','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7730'   , '7720'  , 'Wappen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7720'   , '7710'  , 'Flaggen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7700'   , '7600'  , 'Religionen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '7600'   , '7630'  , 'Hinduismus','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7630'   , '7620'  , 'Buddhismus','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7620'   , '7610'  , 'Islam','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '7610'   , '7611'  , 'Koran','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7600'   , '7500'  , 'staatliche und andere Organisationen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '7500'   , '7550'  , 'Pfadfinder','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '7550'   , '7552'  , 'Pioniere','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7552'   , '7551'  , 'Pfadfindertreffen und Embleme','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7550'   , '7540'  , 'Hilfs- und Wohltätigkeitsorganisationen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '7540'   , '7541'  , 'Malteser, Johanniter','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7540'   , '7530'  , 'Rotes Kreuz / Roter Halbmond','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7530'   , '7520'  , 'Feuerwehr','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7520'   , '7510'  , 'Polizei','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7500'   , '7400'  , 'Staat und Gesellschaft','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '7400'   , '7420'  , 'Sozialversicherung','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7420'   , '7410'  , 'Gewaltenteilung','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7400'   , '7300'  , 'Regierungen Parlamente','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '7300'   , '7310'  , 'Politiker','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7300'   , '7200'  , 'Erklärungen, Vereinbarungen, Verträge, Konferenzen, Kongresse','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7200'   , '7100'  , 'Jahrestage','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '7100'   , '7120'  , '100 Jahre Briefmarken','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7120'   , '7110'  , 'Tag der Briefmarke','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '7000'   , '6000'  , 'Wirtschaft, Wissenschaft, Forschung und Technik','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '6000'   , '6800'  , 'Wehrtechnik','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '6800'   , '6810'  , 'Waffen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6800'   , '6700'  , 'Ingenieurwissenschaften','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6700'   , '6600'  , 'Geisteswissenschaften','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '6600'   , '6630'  , 'Phlilologie','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6630'   , '6620'  , 'Theologie','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6620'   , '6610'  , 'Philosophie','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6600'   , '6500'  , 'Medizin','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '6500'   , '6510'  , 'Gesundheitsdienste','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '6510'   , '6511'  , 'Tuberkolose','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6500'   , '6400'  , 'Naturwissenschaften','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '6400'   , '6460'  , 'Geologie, Mineralogie, Paläontologie','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6460'   , '6450'  , 'Biologie','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6450'   , '6440'  , 'Chemie','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6440'   , '6430'  , 'Physik','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6430'   , '6420'  , 'Astrologie, Sternzeichen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6420'   , '6410'  , 'Mathematik','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6400'   , '6300'  , 'Messen, Tagungen, Ausstellungen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '6300'   , '6320'  , 'Leipziger Messe','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6320'   , '6310'  , 'Briefmarkenausstellungen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6300'   , '6200'  , 'Geld, Siegel, Orden, Briefmarken','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '6200'   , '6250'  , 'Orden','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6250'   , '6240'  , 'Siegel','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6240'   , '6230'  , 'Stempel','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6230'   , '6220'  , 'Briefmarken','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6220'   , '6210'  , 'Geld','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6200'   , '6100'  , 'wirtschaftliche Sektoren','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '6100'   , '6180'  , 'Presse, Journalismus, Druck','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '6180'   , '6183'  , 'Plakat','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6183'   , '6182'  , 'Druck','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6182'   , '6181'  , 'Zeitung','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6180'   , '6170'  , 'Dienstleistungen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '6170'   , '6176'  , 'EDV, Computer','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6176'   , '6175'  , 'Kommunikation','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6175'   , '6174'  , 'Transport','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6174'   , '6173'  , 'Handel','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6173'   , '6172'  , 'Versicherungen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6172'   , '6171'  , 'Banken','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6170'   , '6160'  , 'Fischerei, Tierzucht','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6160'   , '6150'  , 'Land- und Forstwirtschaft','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6150'   , '6140'  , 'produzierendes Gewerbe','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '6140'   , '6142'  , 'Handwerk','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6142'   , '6141'  , 'Industrie','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6140'   , '6130'  , 'Erdöl','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6130'   , '6120'  , 'Bergbau, Energietechnik','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '6120'   , '6122'  , 'Kraftwerk','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6122'   , '6121'  , 'Bergbau','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6120'   , '6110'  , 'Weinbau, Braukunst','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '6000'   , '5000'  , 'Sport, Spiel, Unterhaltung','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5000'   , '5700'  , 'sonstige Unterhaltung','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5700'   , '5720'  , 'Zirkus','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5720'   , '5710'  , 'Tanz','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5700'   , '5600'  , 'Spiele','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5600'   , '5630'  , 'Kinderspiele','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5630'   , '5620'  , 'Kartenspiele','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5620'   , '5610'  , 'Brettspiele','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5610'   , '5632'  , 'Mühle/Dame','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5632'   , '5631'  , 'Schach','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5600'   , '5500'  , 'Sonstige Sportarten','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5500'   , '5520'  , 'Flugsport','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5520'   , '5522'  , 'Modellfliegen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5522'   , '5521'  , 'Segelfliegen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5520'   , '5510'  , 'Fischen, Jagd, Schießen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5510'   , '5513'  , 'Jagd','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5513'   , '5512'  , 'Sportschießen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5512'   , '5511'  , 'Angeln','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5500'   , '5400'  , 'Wassersport','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5400'   , '5450'  , 'Wasserski, Jetski','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5450'   , '5440'  , 'Motorschnellboot','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5440'   , '5430'  , 'Segeln','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5430'   , '5420'  , 'Rudern, Kanu','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5420'   , '5410'  , 'Schwimmen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5400'   , '5300'  , 'Wintersport','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5300'   , '5330'  , 'Bob, Rodeln','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5330'   , '5332'  , 'Rodeln','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5332'   , '5331'  , 'Bob','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5330'   , '5320'  , 'Eissport','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5320'   , '5323'  , 'Eiskunstlauf','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5323'   , '5322'  , 'Eishockey','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5322'   , '5321'  , 'Eisschnelllauf','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5320'   , '5310'  , 'Ski','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5310'   , '5314'  , 'Biathlon','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5314'   , '5313'  , 'Skispringen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5313'   , '5312'  , 'Ski-Abfahrt/Slalom','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5312'   , '5311'  , 'Ski-Langlauf','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5300'   , '5200'  , 'Sport im Freien oder in der Halle','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5200'   , '5290'  , 'Reitsport','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5290'   , '5292'  , 'Dressur','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5292'   , '5291'  , 'Springreiten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5290'   , '5280'  , 'Kampfsport, Schwerathletik','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5280'   , '5284'  , 'Boxen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5284'   , '5283'  , 'Ringen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5283'   , '5282'  , 'Judo, Karate','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5282'   , '5281'  , 'Gewichtheben','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5280'   , '5270'  , 'Motorsport','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5270'   , '5273'  , 'Ralley','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5273'   , '5272'  , 'Motorradsport','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5272'   , '5271'  , 'Formel 1','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5270'   , '5260'  , 'Radsport','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5260'   , '5250'  , 'Wandern, Bergsteigen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5250'   , '5240'  , 'Gymnastik, Turnen, Leichtathletik','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5240'   , '5244'  , 'Rollschuhlaufen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5244'   , '5243'  , 'Jogging','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5243'   , '5242'  , 'Leichtathletik','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5242'   , '5241'  , 'Gymnastik, Turnen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5240'   , '5230'  , 'Ballspiele','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5230'   , '5238'  , 'Hockey','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5238'   , '5237'  , 'Volleyball','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5237'   , '5236'  , 'Baseball','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5236'   , '5235'  , 'Tischtennis','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5235'   , '5234'  , 'Tennis','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5234'   , '5233'  , 'Basketball','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5233'   , '5232'  , 'Handball','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5232'   , '5231'  , 'Fußball','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5230'   , '5220'  , 'Bewegungs- und Geschicklichkeitsspiele','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5220'   , '5210'  , 'Spiele und Erholung im Freien allgemein','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5200'   , '5100'  , 'Organisationen, Veranstaltungen, Wettbewerbe','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5100'   , '5180'  , 'Sportorganisationen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5180'   , '5184'  , 'FIDE und andere Schachorganisationen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5184'   , '5183'  , 'DFB','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5183'   , '5182'  , 'UEFA','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5182'   , '5181'  , 'FIFA','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5180'   , '5170'  , 'Nationale Sportwettbewerbe','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5170'   , '5171'  , 'Deutsche Meisterschaft','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5170'   , '5160'  , 'internationale Sportwettbewerbe','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5160'   , '5165'  , 'Militärmeisterschaften','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5165'   , '5164'  , 'Spartakiade','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5164'   , '5163'  , 'Europameisterschaften','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5163'   , '5162'  , 'Kontinentalmeisterschaften','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5162'   , '5161'  , 'Weltmeistenschaften','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5160'   , '5150'  , 'Sportstadien','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5150'   , '5140'  , 'Regatten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5140'   , '5130'  , 'Europameisterschaften Fußball','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5130'   , '5120'  , 'Weltmeisterschaften Fußball','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5120'   , '5126'  , 'FIFA WM Mexiko 1970 1986','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5126'   , '5125'  , 'FIFA WM England 1966','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5125'   , '5124'  , 'FIFA WM Italien 1934 1990','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5124'   , '5123'  , 'FIFA WM Spanien 1982','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5123'   , '5122'  , 'FIFA WM Deutschland 1974 2006','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5122'   , '5121'  , 'FIFA WM Argentinien 1978','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5120'   , '5110'  , 'Olympia','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '5110'   , '5119'  , 'Winterolympiade','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5119'   , '5118'  , 'Sommerolympiade','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5118'   , '5117'  , 'Mexiko Sommer 1968','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5117'   , '5116'  , 'Moskau Sommer 1980','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5116'   , '5115'  , 'Montreal Sommer 1976','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5115'   , '5114'  , 'Innsbruck Winter 1964, 1976','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5114'   , '5113'  , 'Rom Sommer 1960','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5113'   , '5112'  , 'Sapporo 1972 Winter','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5112'   , '5111'  , 'München 1972 Sommer','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '5000'   , '4000'  , 'Kunst,Musik, Lebensformen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4000'   , '4900'  , 'Cartoons','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4900'   , '4920'  , 'Cartoons von Warner Brothers','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4920'   , '4910'  , 'Cartoons von Walt Disney','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4910'   , '4911'  , 'Mickey Mouse / Donald Duck','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4900'   , '4800'  , 'Christliche Motive','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4800'   , '4840'  , 'Kichliche Treffen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4840'   , '4844'  , 'Ökumenische Treffen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4844'   , '4843'  , 'Evangelische Kirchentage','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4843'   , '4842'  , 'Eucharistische Kongresse','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4842'   , '4841'  , 'Katholikentage','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4840'   , '4830'  , 'christliche Gemälde','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4830'   , '4820'  , 'christliche Feste','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4820'   , '4822'  , 'Ostern','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4822'   , '4821'  , 'Weihnachten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4820'   , '4810'  , 'christliche Motive/Skulpturen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4810'   , '4813'  , 'Heilige','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4813'   , '4812'  , 'Engel','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4812'   , '4811'  , 'Madonnen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4800'   , '4700'  , 'Lebensformen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4700'   , '4730'  , 'Tourismus','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4730'   , '4720'  , 'Volksfeste, Folklore, Karneval','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4720'   , '4724'  , 'Volksfest','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4724'   , '4723'  , 'Neujahr','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4723'   , '4722'  , 'Karneval','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4722'   , '4721'  , 'Folklore','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4720'   , '4710'  , 'Märchen, Sagen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4710'   , '4714'  , 'Allegorien','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4714'   , '4713'  , 'Mythen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4713'   , '4712'  , 'Sagen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4712'   , '4711'  , 'Märchen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4700'   , '4600'  , 'Bekleidung','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4600'   , '4630'  , 'Uniform','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4630'   , '4634'  , 'Ritter','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4634'   , '4633'  , 'Uniformen der Polizei/Feuerwehr/Hilfsorganisationen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4633'   , '4632'  , 'Pfadfinderuniform','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4632'   , '4631'  , 'Militärische Uniformen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4630'   , '4620'  , 'Tracht','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4620'   , '4610'  , 'Kleidung','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4600'   , '4500'  , 'Archäologische Funde, Sakralgegenstände','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4500'   , '4520'  , 'Sakralgegenstände','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4520'   , '4510'  , 'Archäologische Funde','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4500'   , '4400'  , 'Kunstgewerbe','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4400'   , '4470'  , 'optische Geräte','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4470'   , '4460'  , 'Uhren','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4460'   , '4450'  , 'Textilkunst','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4450'   , '4440'  , 'Bücher','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4440'   , '4444'  , 'Ziffer','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4444'   , '4443'  , 'Text','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4443'   , '4442'  , 'Buchstabe','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4442'   , '4441'  , 'Handschrift','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4440'   , '4430'  , 'Spielzeug','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4430'   , '4431'  , 'Teddy','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4430'   , '4420'  , 'Masken','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4420'   , '4410'  , 'Puppen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4400'   , '4300'  , 'Fernsehen, Theater, Film','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4300'   , '4340'  , 'Fernsehen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4340'   , '4330'  , 'Filme','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4330'   , '4320'  , 'Theaterstücke','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4320'   , '4310'  , 'Oper/Operette','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4300'   , '4200'  , 'Musik','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4200'   , '4220'  , 'Noten, Lieder','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4220'   , '4210'  , 'Instrumente','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4200'   , '4100'  , 'Bildende Kunst','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4100'   , '4150'  , 'Goldschmiedearbeit, Schmuck','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4150'   , '4140'  , 'Keramik','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4140'   , '4142'  , 'Geschirr','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4142'   , '4141'  , 'Porzellan','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4140'   , '4130'  , 'Skulpturen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4130'   , '4120'  , 'Akt','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4120'   , '4110'  , 'Gemälde','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '4110'   , '4112'  , 'Stilleben','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4112'   , '4111'  , 'Porträts','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '4000'   , '3000'  , 'Immobilien','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3000'   , '3600'  , 'Architektur','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3600'   , '3500'  , 'Kirchen, Klöster, Burgen, Schlösser','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3500'   , '3560'  , 'archäologische Bauten','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3560'   , '3561'  , 'Pyramiden','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3560'   , '3550'  , 'Denkmäler','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3550'   , '3551'  , 'Brunnen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3550'   , '3540'  , 'Burgen, Schlösser','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3540'   , '3530'  , 'Friedhöfe, Grabmäler','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3530'   , '3520'  , 'Klöster','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3520'   , '3510'  , 'Kirchen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3510'   , '3512'  , 'Tempel','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3512'   , '3511'  , 'Moscheen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3500'   , '3400'  , 'Brücken, Viadukte, Tunnel, Türme','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3400'   , '3440'  , 'Türme','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3440'   , '3443'  , 'Windmühlen, Mühlen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3443'   , '3442'  , 'Leuchttürme','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3442'   , '3441'  , 'Fernsehtürme','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3440'   , '3430'  , 'Tunnel','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3430'   , '3420'  , 'Viadukte','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3420'   , '3421'  , 'Aquädukt','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3420'   , '3410'  , 'Brücken','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3400'   , '3300'  , 'Schmuck an Gebäuden','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3300'   , '3320'  , 'Skulpturen an Gebäuden','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3320'   , '3310'  , 'Säulen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3300'   , '3200'  , 'Wohngebäude','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3200'   , '3240'  , 'Hotels','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3240'   , '3230'  , 'Hochhäuser','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3230'   , '3220'  , 'Bauernhäuser','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3220'   , '3210'  , 'Stadtansichten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3200'   , '3100'  , 'Öffentliche Gebäude','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3100'   , '3150'  , 'Kunst/Kultur','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3150'   , '3152'  , 'Theater/Oper','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3152'   , '3151'  , 'Museen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3150'   , '3140'  , 'Wirtschaftsgebäude','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3140'   , '3142'  , 'Bergwerk','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3142'   , '3141'  , 'Industrie, Fabrikgebäude','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3140'   , '3130'  , 'Politik','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3130'   , '3132'  , 'Gerichte','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3132'   , '3131'  , 'Regierungsgebäude','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3130'   , '3120'  , 'Verkehrsbauten','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3120'   , '3126'  , 'Kanal','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3126'   , '3125'  , 'Schienen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3125'   , '3124'  , 'Straßen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3124'   , '3123'  , 'Schiffshafen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3123'   , '3122'  , 'Flughafen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3122'   , '3121'  , 'Bahnhöfe','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3120'   , '3110'  , 'Schulen ,Universitäten','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '3110'   , '3114'  , 'Erwachsenenbildung','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3114'   , '3113'  , 'Hochschulen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3113'   , '3112'  , 'Universitäten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3112'   , '3111'  , 'Schulen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '3000'   , '2000'  , 'Verkehrsmittel','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '2000'   , '2500'  , 'im All','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '2500'   , '2530'  , 'Satellit','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2530'   , '2520'  , 'Raumschiff','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2520'   , '2510'  , 'Rakete','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2500'   , '2400'  , 'in der Luft','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '2400'   , '2450'  , 'Fallschirm','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2450'   , '2440'  , 'Ballon','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2440'   , '2430'  , 'Luftschiff/Zeppelin','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2430'   , '2420'  , 'Hubschrauber','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2420'   , '2410'  , 'Flugzeug','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2400'   , '2300'  , 'auf dem Wasser','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '2300'   , '2340'  , 'Surfen/Windsurfen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2340'   , '2330'  , 'Boot','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2330'   , '2320'  , 'Flugboot','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2320'   , '2310'  , 'Schiff','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '2310'   , '2313'  , 'Containerschiff','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2313'   , '2312'  , 'Motorschiff','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2312'   , '2311'  , 'Segelschiff','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2300'   , '2200'  , 'auf den Land','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '2200'   , '2250'  , 'Schlitten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2250'   , '2240'  , 'Kutsche/Pferdewagen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '2240'   , '2241'  , 'Postkutsche','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2240'   , '2230'  , 'Fahrrad','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2230'   , '2220'  , 'Motorrad','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2220'   , '2210'  , 'Auto','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '2210'   , '2216'  , 'Bus','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2216'   , '2215'  , 'Militärfahrzeug','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2215'   , '2214'  , 'Baufahrzeug','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2214'   , '2213'  , 'LKW','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2213'   , '2212'  , 'Landwirtschaftliches Fahrzeug','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2212'   , '2211'  , 'PKW','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2200'   , '2100'  , 'auf Führungssystemen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '2100'   , '2140'  , 'Seilbahn','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2140'   , '2130'  , 'Magnetschwebebahn','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2130'   , '2120'  , 'Straßenbahn','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2120'   , '2110'  , 'Eisenbahn','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '2110'   , '2114'  , 'Dampflok','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2114'   , '2113'  , 'Waggon','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2113'   , '2112'  , 'Nahverkehr (U-Bahn, S-Bahn)','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2112'   , '2111'  , 'Lok','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '2000'   , '1000'  , 'Menschen, Pflanzen, Lebensräume','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1000'   , '1300'  , 'Lebensräume','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1300'   , '1390'  , 'Bildung, Schule','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1390'   , '1380'  , 'Gesundheit, Leben, Familie','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1380'   , '1382'  , 'Familie','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1382'   , '1381'  , 'Gesundheit','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1380'   , '1370'  , 'Natur- und Umweltschutz','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1370'   , '1371'  , 'Nationalparks','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1370'   , '1360'  , 'Mineralien','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1360'   , '1362'  , 'Edelsteine/Diamanten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1362'   , '1361'  , 'Erze','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1360'   , '1350'  , 'Neue Lebensräume','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1350'   , '1353'  , 'Widerstand, Krieg','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1353'   , '1352'  , 'Kolonisation','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1352'   , '1351'  , 'Expedition','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1350'   , '1340'  , 'Weltraum','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1340'   , '1345'  , 'Mond','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1345'   , '1344'  , 'Sonne','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1344'   , '1343'  , 'Kometen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1343'   , '1342'  , 'Planeten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1342'   , '1341'  , 'Sterne','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1340'   , '1330'  , 'Luft','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1330'   , '1320'  , 'Landschaft, Wetter','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1320'   , '1323'  , 'Antarktis','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1323'   , '1322'  , 'Wetter, Wolken','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1322'   , '1321'  , 'Landschaft','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1320'   , '1310'  , 'Wasser','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1310'   , '1313'  , 'Meer','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1313'   , '1312'  , 'See','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1312'   , '1311'  , 'Fluss','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1300'   , '1200'  , 'Pflanzen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1200'   , '1280'  , 'Heilpflanzen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1280'   , '1270'  , 'Nutzpflanzen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1270'   , '1274'  , 'Tabak','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1274'   , '1273'  , 'Gemüse','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1273'   , '1272'  , 'Obst','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1272'   , '1271'  , 'Getreide','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1270'   , '1260'  , 'Pilze','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1260'   , '1250'  , 'Blumen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1250'   , '1251'  , 'Rosen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1250'   , '1240'  , 'Gräser/Sträucher','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1240'   , '1230'  , 'Bäume/Früchte/Blüten','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1230'   , '1233'  , 'Blüten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1233'   , '1232'  , 'Früchte','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1232'   , '1231'  , 'Bäume','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1230'   , '1220'  , 'Kakteen, Proteusgewächse, Palmen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1220'   , '1223'  , 'Proteusgewächse','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1223'   , '1222'  , 'Palmen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1222'   , '1221'  , 'Kakteen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1220'   , '1210'  , 'Algen, Flechten, Moose, Farne','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1210'   , '1213'  , 'Farne','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1213'   , '1212'  , 'Flechten, Moose','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1212'   , '1211'  , 'Algen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1200'   , '1100'  , 'Menschen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1100'   , '1190'  , 'Kinder/Jugend','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1190'   , '1180'  , 'allgemein berühmt','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1180'   , '1170'  , 'Literatur, Theater, Film','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1170'   , '1173'  , 'Regisseure/Intendanten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1173'   , '1172'  , 'Schauspieler','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1172'   , '1171'  , 'Schriftsteller','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1170'   , '1160'  , 'Künstler/Musiker','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1160'   , '1164'  , 'Sänger','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1164'   , '1163'  , 'Musiker','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1163'   , '1162'  , 'Komponisten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1162'   , '1161'  , 'Künstler','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1160'   , '1150'  , 'Wirtschaftler','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1150'   , '1155'  , 'Ärzte, Krankenschwestern','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1155'   , '1154'  , 'Bauer /Landwirtschaftliche Arbeiter','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1154'   , '1153'  , 'Bauarbeiter','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1153'   , '1152'  , 'Industriearbeiter','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1152'   , '1151'  , 'Bänker','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1150'   , '1140'  , 'Wissenschaftler','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1140'   , '1146'  , 'Juristen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1146'   , '1145'  , 'Sozialwissenschaftler','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1145'   , '1144'  , 'Mathematiker','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1144'   , '1143'  , 'Geowissenschaftler','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1143'   , '1142'  , 'Wirtschaftwissenschaftler','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1142'   , '1141'  , 'Naturwissenschaftler','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1140'   , '1130'  , 'Politik/Geschichte','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1130'   , '1139'  , 'Ferdinand Graf von Zeppelin','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1139'   , '1138'  , 'Sir Rowland Hill','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1138'   , '1137'  , 'Albert Schweitzer','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1137'   , '1136'  , 'historische Persönlichkeit','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1136'   , '1135'  , 'Adel','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1135'   , '1134'  , 'Politiker','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1134'   , '1133'  , 'Präsident','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1133'   , '1132'  , 'Englische Königinnen und Könige','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1133'   , '1131'  , 'Monarch','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1130'   , '1120'  , 'Religion','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1120'   , '1128'  , 'Heiliger','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1128'   , '1127'  , 'Naturreligionen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1127'   , '1126'  , 'Hinduisten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1126'   , '1125'  , 'Buddhisten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1125'   , '1124'  , 'Muslime','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1124'   , '1123'  , 'Protestantischer Theologe','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1123'   , '1122'  , 'Bischof/Kath. Theologe','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1122'   , '1121'  , 'Papst','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1120'   , '1110'  , 'Nobelpreisträger','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '1110'   , '1113'  , 'Naturwissenschaft','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1113'   , '1112'  , 'Literatur','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1112'   , '1111'  , 'Frieden','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '1000'   , '0000'  , 'Tiere, nicht menschl Lebensformen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0000'   , '0900'  , 'Urtiere','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0900'   , '0930'  , 'Ammoniten/Fossilien','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0930'   , '0920'  , 'Ur-Säuger','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0920'   , '0910'  , 'Saurier','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0900'   , '0800'  , 'Säugetiere','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0800'   , '0860'  , 'Schafe, Ziegen, Schweine','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0860'   , '0866'  , 'Wildschwein','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0866'   , '0865'  , 'Hausschwein','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0865'   , '0864'  , 'Widder','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0864'   , '0863'  , 'Steinbock','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0863'   , '0862'  , 'Ziege','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0862'   , '0861'  , 'Schafe','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0860'   , '0850'  , 'Nagetiere','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0850'   , '0857'  , 'Murmeltiere/Erdmännchen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0857'   , '0856'  , 'Biber','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0856'   , '0855'  , 'Hörnchen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0855'   , '0854'  , 'Mäuse/Ratten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0854'   , '0853'  , 'Meerschweinchen/Hamster','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0853'   , '0852'  , 'Kaninchen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0852'   , '0851'  , 'Hase','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0850'   , '0840'  , 'Geweihträger/andere Paarhufer','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0840'   , '0847'  , 'Kamele /Lama','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0847'   , '0846'  , 'Giraffen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0846'   , '0845'  , 'Rehe/Hirsche/Elche/Ren','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0845'   , '0844'  , 'Antilope','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0844'   , '0843'  , 'Büffel','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0843'   , '0842'  , 'Gnu','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0842'   , '0841'  , 'Kuh','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0840'   , '0830'  , 'Pferdeartige','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0830'   , '0834'  , 'Esel','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0834'   , '0833'  , 'Pony','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0833'   , '0832'  , 'Zebra','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0832'   , '0831'  , 'Hauspferde','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0830'   , '0820'  , 'Hundeartige','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0820'   , '0825'  , 'Füchse','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0825'   , '0824'  , 'Koyote','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0824'   , '0823'  , 'Wolf','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0823'   , '0822'  , 'Hyänen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0822'   , '0821'  , 'Haushunde','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0820'   , '0810'  , 'Katzenartige','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0810'   , '0816'  , 'Puma, Panther','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0816'   , '0815'  , 'Luchs','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0815'   , '0814'  , 'Leopard, Gepard','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0814'   , '0813'  , 'Tiger','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0813'   , '0812'  , 'Löwen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0812'   , '0811'  , 'Hauskatzen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0800'   , '0700'  , 'Säugetiere/Beuteltiere','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0700'   , '0770'  , 'Übrige','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0770'   , '0778'  , 'Schnabeltier','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0778'   , '0777'  , 'Maulwurf','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0777'   , '0778'  , 'Igel','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0776'   , '0775'  , 'Tapir','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0775'   , '0774'  , 'Erdferkel','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0774'   , '0773'  , 'Gürteltier','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0773'   , '0772'  , 'Faultier','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0772'   , '0771'  , 'Ameisenbär','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0770'   , '0760'  , 'Flugsäuger','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0760'   , '0762'  , 'Fledermäuse','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0762'   , '0761'  , 'Flughunde','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0760'   , '0750'  , 'Marder','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0750'   , '0754'  , 'Vielfraß','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0754'   , '0753'  , 'Dachse','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0753'   , '0752'  , 'Otter','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0752'   , '0751'  , 'Wiesel','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0750'   , '0740'  , 'Affen/Halbaffen','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0740'   , '0745'  , 'Orang-Utan','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0745'   , '0744'  , 'Gorilla','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0744'   , '0743'  , 'Schimpansen, Bonobo','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0743'   , '0742'  , 'Halbaffen/Meerkatzen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0742'   , '0741'  , 'Hominiden','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0740'   , '0730'  , 'Bären','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0730'   , '0735'  , 'Kleinbären','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0735'   , '0734'  , 'Koala','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0734'   , '0733'  , 'Panda','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0733'   , '0732'  , 'Eisbären','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0732'   , '0731'  , 'Braunbären','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0730'   , '0720'  , 'Großsäuger','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0720'   , '0726'  , 'Känguru','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0726'   , '0725'  , 'Robben','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0725'   , '0724'  , 'Dugong','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0724'   , '0723'  , 'Nilpferd','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0723'   , '0722'  , 'Nashörner','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0722'   , '0721'  , 'Elefanten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0720'   , '0710'  , 'Meeressäuger','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0710'   , '0712'  , 'Delfine','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0712'   , '0711'  , 'Wale','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0700'   , '0600'  , 'Vögel','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0600'   , '0650'  , 'Pinguine','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0650'   , '0654'  , 'Schopf-Pinguine','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0654'   , '0653'  , 'Zügel-Pinguine','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0653'   , '0652'  , 'Königspinguine','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0652'   , '0651'  , 'Kaiserpinguine','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0650'   , '0640'  , 'Lumen/Tölpel','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0640'   , '0630'  , 'Laufvögel','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0630'   , '0633'  , 'Kiwi','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0633'   , '0632'  , 'Emu','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0632'   , '0631'  , 'Strauß','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0630'   , '0620'  , 'Kleinvögel','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0620'   , '0627'  , 'Papageien/Sittiche','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0627'   , '0626'  , 'Kranich/Storch/Reiher','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0626'   , '0625'  , 'Möwe/Albatros','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0625'   , '0624'  , 'Ente/Gans/Schwan','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0624'   , '0623'  , 'Sperling','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0623'   , '0622'  , 'Hühner/Auerhähne/Fasane','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0622'   , '0621'  , 'Tauben','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0620'   , '0610'  , 'Raubvögel','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0610'   , '0615'  , 'Raben','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0615'   , '0614'  , 'Eule','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0614'   , '0613'  , 'Falke','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0613'   , '0612'  , 'Geier','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0612'   , '0611'  , 'Adler','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0600'   , '0500'  , 'Reptilien/Lurche','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0500'   , '0560'  , 'Frösche/Kröten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0560'   , '0550'  , 'Lurche/Salamander','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0550'   , '0540'  , 'Schlangen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0540'   , '0530'  , 'Echsen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0530'   , '0520'  , 'Schildkröten','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0520'   , '0510'  , 'Krokodile/Kaiman','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0500'   , '0400'  , 'Fische','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0400'   , '0440'  , 'Meeresfische','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0440'   , '0430'  , 'Korallenfische','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0430'   , '0420'  , 'Süßwasserfische','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0420'   , '0410'  , 'Haie/Rochen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0400'   , '0300'  , 'Weichtiere/Meerestiere','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0300'   , '0380'  , 'Tintenfisch/Kraken','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0380'   , '0370'  , 'Seesterne','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0370'   , '0360'  , 'Krebse','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0360'   , '0350'  , 'Seepferdchen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0350'   , '0340'  , 'Korallen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0340'   , '0330'  , 'Quallen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0330'   , '0320'  , 'Schnecken','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0320'   , '0310'  , 'Muscheln','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0300'   , '0200'  , 'Insekten, Spinnen, Schädlinge','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0200'   , '0270'  , 'Flöhe/Wanzen/Schaben','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0270'   , '0260'  , 'Skorpion','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0260'   , '0250'  , 'Spinnen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0250'   , '0240'  , 'Flügellose','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0240'   , '0242'  , 'Schrecken/Grillen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0242'   , '0241'  , 'Ameisen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0240'   , '0230'  , 'Käfer','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0230'   , '0220'  , 'Schmetterlinge','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0220'   , '0223'  , 'Raupen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0223'   , '0222'  , 'Nachtfalter','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0222'   , '0221'  , 'Tagfalter','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0220'   , '0210'  , 'Fluginsekten','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0210'   , '0213'  , 'Libellen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0213'   , '0212'  , 'Fliegen','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0212'   , '0211'  , 'Bienen, Wespen, Hummeln','');
  EXEC SP_HIERACHY_ADD_BEFORE('DESIGN', '0200'   , '0100'  , 'niedere Tiere','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0100'   , '0110'  , 'Gliedertiere','');
  EXEC SP_HIERACHY_ADD_CHILD ('DESIGN', '0110'   , '0111'  , 'Würmer','');